name: taleb
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: 
  flutter_spinkit: 
  modal_progress_hud_nsn: any
  sqflite: 
  intl: 
  url_launcher: 
  shared_preferences: 
  share: 
  get: 
  flutter: 
    sdk: flutter
  carousel_slider: 
  smooth_page_indicator: 
  flutter_typeahead: 
  http: 
  google_fonts: 
  either_dart: 
  flutter_otp_text_field: 
  flutter_svg: 

dev_dependencies: 
  flutter_lints: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/splash/
    - assets/icons/

  uses-material-design: true

  fonts:
    - family: Inspiration
      fonts:
        - asset: fonts/JosefinSans-VariableFont_wght.ttf

