name: taleb
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: 
  flutter_spinkit: 
  modal_progress_hud_nsn: any
  sqflite: 
  intl: 
  url_launcher: ^6.1.14 
  shared_preferences: ^2.2.2 
  share: 
  get: 
  flutter: 
    sdk: flutter
  carousel_slider: 
  smooth_page_indicator: 
  flutter_typeahead: 
  http: 
  google_fonts: 
  either_dart: 
  flutter_otp_text_field: 
  flutter_svg: 
  comment_box: ^0.0.18
  dots_indicator: ^3.0.0
  photo_view: ^0.14.0
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  flutter_ringtone_player: ^3.2.0
  jiffy: ^6.2.1
  cloud_firestore: ^4.12.0
  firebase_storage: ^11.4.0
  firebase_auth: ^4.12.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  gallery_saver: ^2.3.2
  emoji_picker_flutter: ^1.6.2
  # awesome_notifications: ^0.8.2 this packadge is to show number of notification whene i'm out of my app
  # jiffy: ^6.2.1
  # flutter_localization: ^0.1.14

dev_dependencies: 
  flutter_lints: 
  flutter_test: 
    sdk: flutter

flutter: 
  generate: true
  assets: 
    - assets/splash/
    - assets/icons/

  uses-material-design: true

  fonts: 
    - family: Bitter
      fonts:
        - asset: fonts/Bitter-Medium.ttf

    - family: Bitter_italic
      fonts:
        - asset: fonts/Bitter-Mediumitalic.ttf