// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuxeg7mp9itg9EQuKejCUvuWZC63NDBU',
    appId: '1:321847682857:web:2b211efa22a57f9f527938',
    messagingSenderId: '321847682857',
    projectId: 'taleb-ac17b',
    authDomain: 'taleb-ac17b.firebaseapp.com',
    storageBucket: 'taleb-ac17b.appspot.com',
    measurementId: 'G-05NM2LLVLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnE6UfTcWm_DoO2m7PNIssoKgqnV_2xM',
    appId: '1:321847682857:android:ba41ad62cacbc5bb527938',
    messagingSenderId: '321847682857',
    projectId: 'taleb-ac17b',
    storageBucket: 'taleb-ac17b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIrDv6Ht5BlDE-ophLIaSD7ptaJxlTjA',
    appId: '1:321847682857:ios:2339cec177dc11f5527938',
    messagingSenderId: '321847682857',
    projectId: 'taleb-ac17b',
    storageBucket: 'taleb-ac17b.appspot.com',
    iosBundleId: 'com.example.taleb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIrDv6Ht5BlDE-ophLIaSD7ptaJxlTjA',
    appId: '1:321847682857:ios:f96aabf48e4af120527938',
    messagingSenderId: '321847682857',
    projectId: 'taleb-ac17b',
    storageBucket: 'taleb-ac17b.appspot.com',
    iosBundleId: 'com.example.taleb.RunnerTests',
  );
}
